professions_list = {
    'Mechanical_engineer': 33,
    'Software_Developer': 43,
    'Technical_writer': 47,
    'Civil_servant': 11,
    'Librarian': 31,
    'Economist': 20,
    'Flight_attendant': 25,
    'Architect': 2,
    'Designer': 18,
    'Physician': 37,
    'Financial_Analyst': 23,
    'Air_traffic_controller': 0,
    'Politician': 39,
    'Police_officer': 38,
    'Artist': 4,
    'Surveyor': 46,
    'Design_Engineer': 17,
    'Chemical_engineer': 9,
    'Hotel_Manager': 28,
    'Dentist': 16,
    'Comedian': 12,
    'Biomedical_Engineer': 6,
    'Graphic_Designer': 27,
    'Computer_hardware_engineer': 13,
    'Petroleum_Engineer': 36,
    'Secretary': 42,
    'Computer_operator': 14,
    'Chartered_Accountant': 7,
    'Technician': 48,
    'Microbiologist': 34,
    'Fashion_Designer': 22,
    'Aviator': 5,
    'Psychologist': 40,
    'Magistrate': 32,
    'Lawyer': 30,
    'Firefighter': 24,
    'Engineer': 21,
    'Official': 35,
    'Analyst': 1,
    'Geologist': 26,
    'Drafter': 19,
    'Statistician': 44,
    'Web_designer': 50,
    'Consultant': 15,
    'Chef': 8,
    'Army_officer': 3,
    'Surgeon': 45,
    'Scientist': 41,
    'Civil_engineer': 10,
    'Industrial_Engineer': 29,
    'Technology_specialist': 49
}

features = ['Income',
            'Age',
            'Experience',
            'Married/Single',
            'House_Ownership',
            'Car_Ownership',
            'Profession',
            'CURRENT_JOB_YRS',
            'CURRENT_HOUSE_YRS']
